pipeline:
  name: git hub test
  identifier: git_hub_test
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: script
        identifier: script
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: false
                    source:
                      type: Inline
                      spec:
                        script: |-
                          ##!/bin/bash
                          pwd
                          echo "Hello world"
                          cd testing
                          ./script.sh
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
