pipeline:
  identifier: Build_testing_1690521631527
  name: Build testing
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: PrashanthKanuka/testing
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: |-
                      echo hello world
                      git clone https://github.com/PrashanthKanuka/testing.git
                      cd testing
                      ./script.sh
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
