pipeline:
  identifier: Build_testing_1690557916145
  name: Build
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1690557902997
        repoName: PrashanthKanuka/testing
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: test
                  spec:
                    shell: Sh
                    command: |-
                      echo hello world
                      pwd
                      cd testing
                      ./script.sh
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
        type: CI
  tags: {}
